vendors_list = [
    "1881 Norway",
    "1st Media",
    "2GIS",
    "365 Things Austin",
    "5280 Magazine",
    "55 Places",
    "84 ROOMS",
    "ADP",
    "AFROPUNK",
    "AOI Bootstrap",
    "Academy Museum",
    "Acris",
    "Acxiom (Canada)",
    "Acxiom (International)",
    "Acxiom (US)",
    "Africa 118",
    "Alewife",
    "Alewife KittyHawk",
    "AllTrails",
    "Amazon Hub",
    "American Marketing Publishing",
    "American Weekender",
    "Apontador",
    "Apontador V2",
    "Apple Business Register",
    "Apple Business Register Direct",
    "Apple Music",
    "Apple Retailers",
    "Apple Rich Data",
    "Apple Service Providers",
    "Apple Stores",
    "Apple TV+",
    "ApplePay",
    "ApplePay Direct",
    "Atlas Obscura",
    "Austin Monthly",
    "Australia Post",
    "Australian Curriculum",
    "AutoMotion",
    "Autopass TW",
    "Ayudante",
    "BIXI",
    "BSI3 MENU BUYER INC",
    "Banque Populaire",
    "BasarSoft",
    "Baxter",
    "BeTomorrow",
    "Birdeye",
    "Blink Network",
    "Bloomberg",
    "Bon Appetit",
    "Book My Show",
    "Booking.com",
    "Boston Magazine",
    "Boston.com",
    "Bright Local",
    "BrightEdge Technologies",
    "Broadsheet",
    "Bumble",
    "Business Connect",
    "Business Connect Generic Agency",
    "Cabana",
    "Caisse d'Epargne",
    "Calm",
    "Canly Co Ltd",
    "CareerArc",
    "Center.ai",
    "ChargePoint",
    "Chatmeter",
    "Checkle, Inc",
    "Chef's Feed",
    "Chope",
    "ChowNow",
    "Chunghwa",
    "Cinema Source",
    "Cirrantic",
    "City Essentials",
    "Clarivate",
    "Clinia Health",
    "Closca",
    "Coffee Meets Bagel",
    "Coinstar",
    "Complex",
    "Concrete Playground",
    "ConnectOM",
    "Consistently",
    "Ctrip",
    "Culinary Backstreets",
    "Culture Crusaders",
    "Culture Trip",
    "Culture Whisper",
    "CultureMap",
    "Curiocity",
    "DAC Group",
    "DEPARTURES",
    "DTG",
    "Danish Agency for Security of Supply",
    "Das Oertliche",
    "DataCentric",
    "DataPlor",
    "Dba Platform",
    "Deduce Technologies",
    "Democracy Works",
    "Der Herold",
    "DestinyCS",
    "Dianping",
    "Digital Bricks",
    "Digital Maas",
    "Dimmi",
    "Direct",
    "Directel Macau",
    "Discover Atlanta",
    "Discover Puerto Rico",
    "Doctor.com",
    "Dottori.it",
    "E-Wego",
    "ESSENCE",
    "EastView",
    "Eat Okra",
    "Ecbo",
    "EcoMovement",
    "Edible Communities",
    "Embrace Someplace",
    "Environmental Protection Agency",
    "European Environment Agency",
    "Eurotunnel Le Shuttle",
    "Evermaps",
    "FATMAP",
    "Factual",
    "Factual.com",
    "Fellow",
    "Fenix",
    "Find A Grave",
    "Find Tap",
    "Find Vaccine Now",
    "Fodors",
    "Fonecta",
    "Ford_EV_ExclusionList",
    "Fotospot",
    "Foursquare",
    "Foursquare V2",
    "Freytag",
    "GAY TIMES",
    "GLBT Historical Society",
    "GNC",
    "Gallaudet University",
    "Gas Buddy",
    "GeoNames",
    "Geospatial Information Authority of Japan",
    "GetYourGuide",
    "Getpin",
    "Getty",
    "GlobeTech Thailand",
    "Gold Coast",
    "Goldenpages IE",
    "Golf Digest",
    "Good Shepherd Engineering",
    "Grab",
    "GreatSchools",
    "Greenfields Sienkiewicz Sp. k.",
    "Grim & Mild",
    "Gulfshore Life",
    "HER",
    "HappyCow",
    "Hawaii.com",
    "Headwaters Co., Ltd.",
    "HealthEngine",
    "Hidden Cities",
    "Hop Culture",
    "Houston Chronicle",
    "Hyperlocal",
    "I Just Love",
    "I LOVE NY",
    "IHS Markit",
    "IPC",
    "IPC MapFan",
    "ITO World Bikeshare",
    "Ignite360 PTY LTD",
    "Impactual",
    "InfoPortugal",
    "Infobel",
    "Inforich-Chargespot",
    "Instacart",
    "Intentionalist",
    "Intents.Mobi",
    "Italia Online",
    "JCDecaux",
    "Jalan",
    "JustDial",
    "KAYAK",
    "KCRW",
    "Keywalker",
    "KingwayTek",
    "Kitty Maps",
    "Kitty Source",
    "KittyHawk",
    "Klook",
    "Komoot",
    "LA Chinatown Firecracker",
    "LVMH",
    "La Fourchette",
    "LastMile Retail",
    "Le Bonbon",
    "Le Fooding",
    "Let's Eat",
    "Library Technologies",
    "Local Clarity",
    "Local Knowledge",
    "Local Knowledge Agency",
    "Local Ranker",
    "Local Strategy",
    "Local View Tech Inc",
    "Localeze",
    "Localistico",
    "Location Bnk",
    "Location3",
    "Lokesuma",
    "Lonely Planet",
    "Look Who Is Charging",
    "Lore",
    "Los Angeles LGBT Center",
    "Los Angeles Times",
    "Los Angeles magazine",
    "Louis Vuitton",
    "Loyal Health, Inc.",
    "Lyft",
    "MAPA",
    "MCH Data",
    "MLS",
    "MLS Season Pass",
    "Macmillan Podcasts",
    "Madame Figaro",
    "Major League Baseball",
    "Malou Food Marketing",
    "Man of Many",
    "Map Data Services",
    "Map Labs Licensing",
    "MapCity",
    "MapFan Directory",
    "MapIT",
    "MapKing",
    "MapKing Buildings",
    "MapmyIndia",
    "Maponics",
    "Maps Indoor",
    "Maps Indoor Occupant",
    "Mapxus",
    "Market Location",
    "Marqii Inc",
    "Menufy",
    "Metrocket (iExit)",
    "Miami & Miami Beach",
    "Michelin",
    "Milestone Internet",
    "Mobal Oy",
    "MomentFeed",
    "Motivate",
    "Mov",
    "Mowof Inc",
    "Mozrest Limited",
    "Murray",
    "My Little Paris",
    "NA Bancard",
    "NGLCC",
    "NTT",
    "NYC LGBT Historic Sites",
    "NYC open data",
    "Narcity",
    "National Geographic",
    "National Park Foundation",
    "National Park Service",
    "Natural Atlas",
    "Naturally Curly",
    "Nature Conservancy",
    "NavAds",
    "Navitime",
    "Neighborhoods",
    "Neustar Localeze",
    "Neutron - EV",
    "Neutron - EV (non-kh)",
    "Neutron - National Park Service",
    "Neutron - Placecard",
    "Neutron - Placecard B",
    "Neutron Ipc",
    "New Orleans",
    "New York Simply",
    "New in Town",
    "OMfire",
    "OddleEats",
    "Olo Restaurant",
    "OpenRice",
    "OpenSalon / Regis Corp",
    "OpenStreetMap",
    "OpenTable",
    "Ordnance Survey",
    "Oregon Essential",
    "Oslo",
    "Outside",
    "POI Augmentation",
    "POI Science",
    "PROXXY Tech",
    "PRX",
    "PST ART",
    "Pages Jaunes",
    "Pages Jaunes Direct",
    "Paris Olympics",
    "Park Serve",
    "Parkopedia",
    "Partoo",
    "PeakVisor",
    "Petal Republic",
    "Philadelphia Inquirer",
    "PinMeTo",
    "Pitchup",
    "Placeable",
    "Places.Travel",
    "PlugShare",
    "Polle",
    "PositionTech",
    "PottersTech",
    "Prior",
    "Quadrant.io",
    "Quandoo",
    "Radio France",
    "Red Bull Records",
    "Red Tricycle",
    "Regio",
    "Religion of Sports",
    "Render SEO",
    "Reputation.com",
    "Resolution Digital",
    "Resy",
    "RetailTune Srl",
    "ReviewTrackers",
    "Rick Steves' Europe",
    "Rio SEO",
    "Roadtrippers",
    "Roaming Hunger",
    "Rocketdata.io",
    "SafeGraph",
    "San Antonio Magazine",
    "San Francisco Chronicle",
    "Schema Compliant",
    "Secret Media Network",
    "SemaConnect",
    "Sensis",
    "Sephora",
    "Sessile",
    "Shazam",
    "Shopify",
    "Siri - Knowledge Graph",
    "Sitchu",
    "Slice (Pizza)",
    "Smithsonian Institution",
    "Social Places",
    "Solv Health",
    "Sonoma County Tourism",
    "Sparkassen",
    "Spoon University",
    "SpotHero",
    "Sprudge",
    "Square",
    "Street Art Cities",
    "Stylist",
    "SurfLine",
    "SweetIQ",
    "Sydney Mardi Gras",
    "Synup",
    "Syspro",
    "TMap SK Telecom",
    "TNet",
    "Tabelog",
    "Tablet Hotels",
    "Takeaway.com Central Core B.V",
    "Teikoku Data Bank",
    "TeleListas",
    "Tennessee Tourism",
    "Tesco",
    "The Athletic",
    "The Boston Globe",
    "The Infatuation",
    "The New Yorker",
    "The Points Guy",
    "The Six Fifty",
    "The Times",
    "The Wall Street Journal",
    "Threenitas S.A.",
    "Thrillist",
    "TikTok",
    "Time Out",
    "Times Square Alliance",
    "Timestorm",
    "Tiqets",
    "TomTom",
    "TomTom MulitNet",
    "Too Good To Go",
    "Top Local",
    "Toronto Life",
    "Toronto Star",
    "Trailforks",
    "Transport for London",
    "Travel Insider",
    "Travel South Dakota",
    "Travel Texas",
    "Treatwell",
    "Trending",
    "Tribeza",
    "Tribune",
    "Trip Advisor",
    "U-Haul",
    "UALA",
    "USGS",
    "USPS",
    "USPS Mailboxes",
    "Uberall",
    "United Airlines",
    "Vaccine Finder (Covid)",
    "Vaccine Finder (Flu)",
    "Vagaro",
    "VanMoof",
    "Velocity Restaurant Reservations",
    "Vendasta",
    "VenueX",
    "Viator",
    "Vietmap",
    "Visit Colorado",
    "Visit Santa Barbara",
    "Visit Singapore",
    "VolunteerMatch",
    "WOWAPPS PTY LTD",
    "WSL",
    "Walgreens",
    "Walnut Medical",
    "Warsaw",
    "Washington Post",
    "Washingtonian",
    "Wcities",
    "Welcome to Chinatown",
    "Where2GetIt (Soci)",
    "Widewail, Inc.",
    "Wikiloc",
    "Wikipedia",
    "Winnie",
    "Wongnai",
    "Yell UK",
    "Yellow Medya",
    "Yellow Pages Group",
    "Yelp",
    "Yext",
    "Yolo Journal",
    "Zagat",
    "ZocDoc",
    "blogTO",
    "eVgo",
    "easy.co.il",
    "echoQuest, Inc.",
    "foodism",
    "g-Xperts",
    "ifoodie",
    "krick.com GmbH + Co. KG",
    "local.ch",
    "ml_pipeline",
    "zipcar",
    "zomato",
]
