# config/dev.yaml
extract:
  data_path: "csv_files/dev_data.csv"

transform:
  required_columns: ["user_id", "created_at"]
  filter_col: "status"
  filter_val: "inactive"

load:
  db_path: "data/dev_etl.db"
  table_name: "dev_events"
  table_schema:
    user_id: TEXT
    created_at: TEXT
    event_type: TEXT

logging:
  log_file: "logs/dev_etl.log"