from config.config import DATA_PATH, DB_PATH, LOG_FILE
from config.config import REQUIRED_COLUMNS, FILTER_COLUMN, FILTER_VALUE
from config.config import TABLE_NAME, TABLE_SCHEMA

# config/prod.yaml
extract:
  data_path: "csv_files/prod_data.csv"
transform:
  required_columns: ["user_id","created_at","event_type"]
  filter_col: "status"
  filter_val: "inactive"
load:
  db_path: "data/prod_etl.db"
  table_name: "events"
  table_schema:
    user_id: TEXT
    created_at: TEXT
    event_type: TEXT
logging:
  log_file: "logs/prod_etl.log"